// packages/janela/templates/solid/files/src/App.jsx
import { createSignal, onMount, For, Show } from "solid-js";
import "./App.css";

export default function App() {
  const [greeting, setGreeting] = createSignal("…");
  const [a, setA] = createSignal(2);
  const [b, setB] = createSignal(40);
  const [sum, setSum] = createSignal(null);
  const [events, setEvents] = createSignal([]);

  // Backend→frontend events. The payload arrives as a value.
  janela.listen("added", (value) =>
    setEvents((prev) => [`host emitted: ${value}`, ...prev]),
  );

  onMount(async () => setGreeting(await janela.invoke("greet", { name: "__NAME__" })));

  const add = async () =>
    setSum(await janela.invoke("add", { a: Number(a()), b: Number(b()) }));

  return (
    <>
      <h1>{greeting()}</h1>
      <p>
        <input type="number" value={a()} onInput={(e) => setA(e.currentTarget.value)} /> +
        <input type="number" value={b()} onInput={(e) => setB(e.currentTarget.value)} />
        <button onClick={add}>add</button>
        <Show when={sum() !== null}><span> = {sum()}</span></Show>
      </p>
      <ul>
        <For each={events()}>{(e) => <li>{e}</li>}</For>
      </ul>
    </>
  );
}

// packages/janela/templates/react/files/src/App.jsx
import { useEffect, useState } from "react";
import "./App.css";

export default function App() {
  const [greeting, setGreeting] = useState("…");
  const [a, setA] = useState(2);
  const [b, setB] = useState(40);
  const [sum, setSum] = useState(null);
  const [events, setEvents] = useState([]);

  useEffect(() => {
    // Backend→frontend events. The payload arrives as a value.
    janela.listen("added", (value) =>
      setEvents((prev) => [`host emitted: ${value}`, ...prev]),
    );
    janela.invoke("greet", { name: "__NAME__" }).then(setGreeting);
  }, []);

  const add = async () =>
    setSum(await janela.invoke("add", { a: Number(a), b: Number(b) }));

  return (
    <>
      <h1>{greeting}</h1>
      <p>
        <input type="number" value={a} onChange={(e) => setA(e.target.value)} /> +
        <input type="number" value={b} onChange={(e) => setB(e.target.value)} />
        <button onClick={add}>add</button>
        {sum !== null && <span> = {sum}</span>}
      </p>
      <ul>
        {events.map((e, i) => (
          <li key={i}>{e}</li>
        ))}
      </ul>
    </>
  );
}
